services:
  neo4j:
    image: neo4j:5-community
    restart: unless-stopped
    user: "1000:1000"
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 20s
    environment:
      - NEO4J_server_memory_heap_max__size=4096m
      - NEO4J_server_memory_pagecache_size=2g
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_AUTH=neo4j/l3tm31n!
    volumes:
      - ../neo4j/data/data:/data
      - ../neo4j/data/logs:/logs
  elasticsearch:
    image: elasticsearch:8.17.3
    restart: unless-stopped
    user: "1000:1000"
    healthcheck:
      test:  curl --fail http://localhost:9200 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 20s
    environment:
      - TAKE_FILE_OWNERSHIP=1
      - ES_JAVA_OPTS=-Xms4g -Xmx4g
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - ../elasticsearch/data:/usr/share/elasticsearch/data
  server:
      image: c2dhunilu/letterbox-server:latest
      restart: unless-stopped
      healthcheck:
        test: wget http://localhost:4000/health || exit 1
        interval: 1s
        timeout: 10s
        retries: 20
        start_period: 20s
      depends_on:
        neo4j:
          condition: service_healthy
        elasticsearch:
          condition: service_healthy
      environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200
        - ELASTICSEARCH_MAX_PARALLEL_UPDATE=2
        - NEO4J_URL=bolt://neo4j:7687
        - NEO4J_LOGIN=neo4j
        - NEO4J_PASSWORD=l3tm31n!
        - NEO4J_DATABASE=neo4j
        - DATA_FOLDER=/var/letterbox
      volumes:
        - ../project/data:/var/letterbox
  client:
    image: c2dhunilu/letterbox-client:latest
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost/ || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 20s
    depends_on:
      server:
        condition: service_healthy
    ports:
      - 80:80
    environment:
      - NGINX_UPSTREAM_SERVER=server:4000
    volumes:
      - ../nginx/data/pdf:/var/www/pdf